# Generated by Django 6.0.3 on 2026-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_songs_playlist_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
