# Generated by Django 6.0.3 on 2026-03-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_playlist_stars_star_playlist_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='stars',
        ),
        migrations.AddField(
            model_name='star',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='app.playlist'),
            preserve_default=False,
        ),
    ]
