# Generated by Django 6.0.3 on 2026-03-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_playlist_stars_star_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
