name: CDP-staging

on:
  workflow_run:
    workflows: ["CDL"]
    types: [completed]
    branches: ["main"]

jobs:
  deploy-to-staging:
    name: Deploy to staging
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to staging
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.STAGING_HOST}}
          username: ${{secrets.STAGING_USER}}
          key: ${{secrets.STAGING_KEY}}
          port: ${{secrets.STAGING_PORT}}
          script: |
            docker compose -f compose.staging.yml pull
            docker compose -f compose.staging.yml up -d
